name: Build and publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
#    inputs:
#      bundle:
#        type: boolean
#        description: Build a mapping bundle.
#      web:
#        type: boolean
#        description: Build the documentation site.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Publish web with Gradle
        run: ./gradlew buildWeb --stacktrace --info
#        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.web == 'true' }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
#        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.web == 'true' }}
        with:
          folder: build/takenaka/web
          commit-message: 'build: update with ${{ github.sha }}'
